# Site
name: 'Léo Carvalho'
description: 'Léo Carvalho é desenvolvedor PHP e C#, com experiência acadêmica nessas linguagens e profissional em outras áreas.'
icon: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'leocarvalho'
email: 'leonardo.cscarvalho@outlook.com.br'
mailchimp-list: 'https://dev.us4.list-manage.com/subscribe/post?u=fb89d629ee9c814bb1e5e7c4e&amp;id=dc4483f2be'
contact: 'https://leocarvalho.dev/#contact-section'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    leo:
      name:           Leonardo
      site:           https://leocarvalho.dev
      avatar:         /assets/images/perfil.webp
      bio:            "Léo é desenvolvedor PHP e C#, tem 24 anos, mora no Guarujá e não vai à praia todo dia (apesar de acreditar que apenas ver o mar já é suficiente para fazê-lo relaxar)."
      email:          leonardo.cscarvalho@outlook.com.br
      twitter:        https://leocarvalho.dev/twitter
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post-ads
      author: leo
      avatar: /assets/images/perfil.webp
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]